### ISSUE TITLE
Profiles don't set required MediaType for the binary resources.

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-camera-go#84]
Per core contracts Reading model validation code, 
https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/reading.go#L153
Binary readings must have the mediaType set, which is accomplished in the device profile resource definitions like this from Device REST sample profile:

```
  - name: jpeg
    description: "JPEG Image binary message"
    properties:
      value:
        { type: "Binary", readWrite: "W", mediaType : "image/jpeg" }
      units:
        { type: "String", readWrite: "R" }

```

Device Camera's profiles do not set `mediaType` for the `Binary` resources.
Example below from camera-bosch.yaml is missing the mediaType setting

```
  - name: "onvif_snapshot"
    description: "snapshot from first ONVIF MediaProfile"
    properties:
      value:
        { type: "Binary", readWrite: "R" }
      units:
        { type: "Binary", readWrite: "R", defaultValue: "ONVIFSnapshot" }
```
